name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Set YML
        run: |
          mkdir -p src/main/resources/config
          echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > src/main/resources/config/application-production.yml
          find src/main/resources

      - name: build gradle
        run: ./gradlew clean build
